### ISSUE TITLE
集成遇到问题

### ISSUE THREAD

**Issue by lihaodong** [yanzhenjie/bintray#1]
Error:Could not find method install() for arguments [bintray_1zey8qbi1kj3zn28ztu8dftql$_run_closure1@4d223906] on project ':updatelibrary' of type org.gradle.api.Project.
只发布到jcenter

**Comment by yanzhenjie** [comment]
我等会儿测试一下，你先用maven手动同步的那个，你不要去做手动同步操作就和只发布到jcenter一样。

**Comment by lihaodong** [comment]
使用maven手动同步的可以 🙏

**Comment by yanzhenjie** [comment]
已经修复了，你可以试试。
