### ISSUE TITLE
"仅发布到Jcenter"的 bintray.gradle 文件有误

### ISSUE THREAD

**Issue by ZhuLeon** [yanzhenjie/bintray#2]
[bintray.gradle](https://raw.githubusercontent.com/yanzhenjie/bintray/master/bintray.gradle) 文件里是这样写的：
```
apply plugin: rootProject.ext.plugins.maven
apply plugin: rootProject.ext.plugins.bintray
```
但是在“二、配置config.gradle文件” 创建的 config.build 里并没有定义:
```
maven      : 'com.github.dcendents.android-maven',
```

**Comment by yanzhenjie** [comment]
有。

**Comment by ZhuLeon** [comment]
你好，我说的这篇文章：[Bintray.md](https://github.com/yanzhenjie/bintray/blob/master/Bintray.md)
具体问题请看下图：
<img width="930" alt="2018-03-31 2 32 06" src="https://user-images.githubusercontent.com/5566667/38160451-a4b0c472-34f0-11e8-85d8-bc8b07af4350.png">

但是 [bintray.gradle](https://raw.githubusercontent.com/yanzhenjie/bintray/master/bintray.gradle) 里却是这么写的：
<img width="446" alt="2018-03-31 3 04 23" src="https://user-images.githubusercontent.com/5566667/38160747-100a1cec-34f5-11e8-8abd-e2f9d7a7545d.png">

**Comment by yanzhenjie** [comment]
等下，马上修复。

**Comment by yanzhenjie** [comment]
已经修复了，谢谢反馈。
